# PHASE 1: WEB SCRAPING

### Importing Libraries

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

### Base URL + Setup

In [3]:
base_url = "http://books.toscrape.com/catalogue/page-{}.html"

data = []

headers = {
    "User-Agent": "Mozilla/5.0"
}

# Rating mapping
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

### Testing Single Page

In [4]:
url = base_url.format(1)

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print("Books found:", len(books))

Books found: 20

### Extract Data from One Page

In [5]:
for book in books:
    
    # Title
    title = book.h3.a["title"]

    # Price (FIXED)
    price = book.find("p", class_="price_color").text
    price = float(re.sub(r"[^\d.]", "", price))

    # Rating
    rating_class = book.p["class"][1]
    rating = rating_map.get(rating_class, 0)

    # Availability
    availability = book.find("p", class_="instock availability").text.strip()

    # Product URL
    link = book.h3.a["href"]
    product_url = "http://books.toscrape.com/catalogue/" + link

    data.append([title, price, rating, availability, product_url])

# Preview
print(data[:5])

[['A Light in the Attic', 51.77, 3, 'In stock', 'http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'], ['Tipping the Velvet', 53.74, 1, 'In stock', 'http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html'], ['Soumission', 50.1, 1, 'In stock', 'http://books.toscrape.com/catalogue/soumission_998/index.html'], ['Sharp Objects', 47.82, 4, 'In stock', 'http://books.toscrape.com/catalogue/sharp-objects_997/index.html'], ['Sapiens: A Brief History of Humankind', 54.23, 5, 'In stock', 'http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html']]

### Full Loop (All Pages)

In [6]:
data = []  # reset before full run

for page in range(1, 51):
    print(f"Scraping page {page}...")

    url = base_url.format(page)
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        
        title = book.h3.a["title"]

        price = book.find("p", class_="price_color").text
        price = float(re.sub(r"[^\d.]", "", price))

        rating_class = book.p["class"][1]
        rating = rating_map.get(rating_class, 0)

        availability = book.find("p", class_="instock availability").text.strip()

        link = book.h3.a["href"]
        product_url = "http://books.toscrape.com/catalogue/" + link

        data.append([title, price, rating, availability, product_url])

    time.sleep(1)  # avoid hitting server too fast

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...

### Creating DataFrame

In [7]:
df = pd.DataFrame(data, columns=[
    "Title", "Price", "Rating", "Availability", "Product_URL"
])

df.head()

,Title,Price,Rating,Availability,Product_URL
0,A Light in the Attic,51.77,3,In stock,http://books.toscrape.com/catalogue/a-light-in...
1,Tipping the Velvet,53.74,1,In stock,http://books.toscrape.com/catalogue/tipping-th...
2,Soumission,50.10,1,In stock,http://books.toscrape.com/catalogue/soumission...
3,Sharp Objects,47.82,4,In stock,http://books.toscrape.com/catalogue/sharp-obje...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,http://books.toscrape.com/catalogue/sapiens-a-...

### Validate Data

In [8]:
print("Shape:", df.shape)
print(df.info())

Shape: (1000, 5)
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   str
 1   Price         1000 non-null   float64
 2   Rating        1000 non-null   int64
 3   Availability  1000 non-null   str
 4   Product_URL   1000 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 39.2 KB
None

### Save CSV

In [9]:
df.to_csv("raw_books_data.csv", index=False)
print("File saved successfully!")

File saved successfully!

## Extracting & Adding Category column by visiting each product page

### Loading Scraped Data

In [10]:
import pandas as pd

df = pd.read_csv("raw_books_data.csv")

df.head()

,Title,Price,Rating,Availability,Product_URL
0,A Light in the Attic,51.77,3,In stock,http://books.toscrape.com/catalogue/a-light-in...
1,Tipping the Velvet,53.74,1,In stock,http://books.toscrape.com/catalogue/tipping-th...
2,Soumission,50.10,1,In stock,http://books.toscrape.com/catalogue/soumission...
3,Sharp Objects,47.82,4,In stock,http://books.toscrape.com/catalogue/sharp-obje...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,http://books.toscrape.com/catalogue/sapiens-a-...

### Importing Required Libraries

In [11]:
import requests
from bs4 import BeautifulSoup
import time

headers = {
    "User-Agent": "Mozilla/5.0"
}

### Testing Category Extraction
### Testing on 1 URL before full run

In [12]:
url = df["Product_URL"][0]

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

# Extract category from breadcrumb
breadcrumb = soup.find("ul", class_="breadcrumb").find_all("li")

category = breadcrumb[2].text.strip()

print("Category:", category)

Category: Poetry

### Creating Function

In [13]:
def get_category(url):
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")
        
        breadcrumb = soup.find("ul", class_="breadcrumb").find_all("li")
        category = breadcrumb[2].text.strip()
        
        return category
    
    except:
        return "Unknown"

### Testing on Few Rows

In [14]:
df_sample = df.head(10).copy()

df_sample["Category"] = df_sample["Product_URL"].apply(get_category)

df_sample

,Title,Price,Rating,Availability,Product_URL,Category
0,A Light in the Attic,51.77,3,In stock,http://books.toscrape.com/catalogue/a-light-in...,Poetry
1,Tipping the Velvet,53.74,1,In stock,http://books.toscrape.com/catalogue/tipping-th...,Historical Fiction
2,Soumission,50.10,1,In stock,http://books.toscrape.com/catalogue/soumission...,Fiction
3,Sharp Objects,47.82,4,In stock,http://books.toscrape.com/catalogue/sharp-obje...,Mystery
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,http://books.toscrape.com/catalogue/sapiens-a-...,History
5,The Requiem Red,22.65,1,In stock,http://books.toscrape.com/catalogue/the-requie...,Young Adult
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,In stock,http://books.toscrape.com/catalogue/the-dirty-...,Business
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,In stock,http://books.toscrape.com/catalogue/the-coming...,Default
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,In stock,http://books.toscrape.com/catalogue/the-boys-i...,Default
9,The Black Maria,52.15,1,In stock,http://books.toscrape.com/catalogue/the-black-...,Poetry

### Applying to Full Dataset

In [15]:
categories = []

for i, url in enumerate(df["Product_URL"]):
    print(f"Processing {i+1}/{len(df)}")

    category = get_category(url)
    categories.append(category)

    time.sleep(1)  # VERY IMPORTANT (avoid blocking)

df["Category"] = categories

Processing 1/1000
Processing 2/1000
Processing 3/1000
Processing 4/1000
Processing 5/1000
Processing 6/1000
Processing 7/1000
Processing 8/1000
Processing 9/1000
Processing 10/1000
Processing 11/1000
Processing 12/1000
Processing 13/1000
Processing 14/1000
Processing 15/1000
Processing 16/1000
Processing 17/1000
Processing 18/1000
Processing 19/1000
Processing 20/1000
Processing 21/1000
Processing 22/1000
Processing 23/1000
Processing 24/1000
Processing 25/1000
Processing 26/1000
Processing 27/1000
Processing 28/1000
Processing 29/1000
Processing 30/1000
Processing 31/1000
Processing 32/1000
Processing 33/1000
Processing 34/1000
Processing 35/1000
Processing 36/1000
Processing 37/1000
Processing 38/1000
Processing 39/1000
Processing 40/1000
Processing 41/1000
Processing 42/1000
Processing 43/1000
Processing 44/1000
Processing 45/1000
Processing 46/1000
Processing 47/1000
Processing 48/1000
Processing 49/1000
Processing 50/1000
Processing 51/1000
Processing 52/1000
Processing 53/1000
Processing 54/1000
Processing 55/1000
Processing 56/1000
Processing 57/1000
Processing 58/1000
Processing 59/1000
Processing 60/1000
Processing 61/1000
Processing 62/1000
Processing 63/1000
Processing 64/1000
Processing 65/1000
Processing 66/1000
Processing 67/1000
Processing 68/1000
Processing 69/1000
Processing 70/1000
Processing 71/1000
Processing 72/1000
Processing 73/1000
Processing 74/1000
Processing 75/1000
Processing 76/1000
Processing 77/1000
Processing 78/1000
Processing 79/1000
Processing 80/1000
Processing 81/1000
Processing 82/1000
Processing 83/1000
Processing 84/1000
Processing 85/1000
Processing 86/1000
Processing 87/1000
Processing 88/1000
Processing 89/1000
Processing 90/1000
Processing 91/1000
Processing 92/1000
Processing 93/1000
Processing 94/1000
Processing 95/1000
Processing 96/1000
Processing 97/1000
Processing 98/1000
Processing 99/1000
Processing 100/1000
Processing 101/1000
Processing 102/1000
Processing 103/1000
Processing 104/1000
Processing 105/1000
Processing 106/1000
Processing 107/1000
Processing 108/1000
Processing 109/1000
Processing 110/1000
Processing 111/1000
Processing 112/1000
Processing 113/1000
Processing 114/1000
Processing 115/1000
Processing 116/1000
Processing 117/1000
Processing 118/1000
Processing 119/1000
Processing 120/1000
Processing 121/1000
Processing 122/1000
Processing 123/1000
Processing 124/1000
Processing 125/1000
Processing 126/1000
Processing 127/1000
Processing 128/1000
Processing 129/1000
Processing 130/1000
Processing 131/1000
Processing 132/1000
Processing 133/1000
Processing 134/1000
Processing 135/1000
Processing 136/1000
Processing 137/1000
Processing 138/1000
Processing 139/1000
Processing 140/1000
Processing 141/1000
Processing 142/1000
Processing 143/1000
Processing 144/1000
Processing 145/1000
Processing 146/1000
Processing 147/1000
Processing 148/1000
Processing 149/1000
Processing 150/1000
Processing 151/1000
Processing 152/1000
Processing 153/1000
Processing 154/1000
Processing 155/1000
Processing 156/1000
Processing 157/1000
Processing 158/1000
Processing 159/1000
Processing 160/1000
Processing 161/1000
Processing 162/1000
Processing 163/1000
Processing 164/1000
Processing 165/1000
Processing 166/1000
Processing 167/1000
Processing 168/1000
Processing 169/1000
Processing 170/1000
Processing 171/1000
Processing 172/1000
Processing 173/1000
Processing 174/1000
Processing 175/1000
Processing 176/1000
Processing 177/1000
Processing 178/1000
Processing 179/1000
Processing 180/1000
Processing 181/1000
Processing 182/1000
Processing 183/1000
Processing 184/1000
Processing 185/1000
Processing 186/1000
Processing 187/1000
Processing 188/1000
Processing 189/1000
Processing 190/1000
Processing 191/1000
Processing 192/1000
Processing 193/1000
Processing 194/1000
Processing 195/1000
Processing 196/1000
Processing 197/1000
Processing 198/1000
Processing 199/1000
Processing 200/1000
Processing 201/1000
Processing 202/1000
Processing 203/1000
Processing 204/1000
Processing 205/1000
Processing 206/1000
Processing 207/1000
Processing 208/1000
Processing 209/1000
Processing 210/1000
Processing 211/1000
Processing 212/1000
Processing 213/1000
Processing 214/1000
Processing 215/1000
Processing 216/1000
Processing 217/1000
Processing 218/1000
Processing 219/1000
Processing 220/1000
Processing 221/1000
Processing 222/1000
Processing 223/1000
Processing 224/1000
Processing 225/1000
Processing 226/1000
Processing 227/1000
Processing 228/1000
Processing 229/1000
Processing 230/1000
Processing 231/1000
Processing 232/1000
Processing 233/1000
Processing 234/1000
Processing 235/1000
Processing 236/1000
Processing 237/1000
Processing 238/1000
Processing 239/1000
Processing 240/1000
Processing 241/1000
Processing 242/1000
Processing 243/1000
Processing 244/1000
Processing 245/1000
Processing 246/1000
Processing 247/1000
Processing 248/1000
Processing 249/1000
Processing 250/1000
Processing 251/1000
Processing 252/1000
Processing 253/1000
Processing 254/1000
Processing 255/1000
Processing 256/1000
Processing 257/1000
Processing 258/1000
Processing 259/1000
Processing 260/1000
Processing 261/1000
Processing 262/1000
Processing 263/1000
Processing 264/1000
Processing 265/1000
Processing 266/1000
Processing 267/1000
Processing 268/1000
Processing 269/1000
Processing 270/1000
Processing 271/1000
Processing 272/1000
Processing 273/1000
Processing 274/1000
Processing 275/1000
Processing 276/1000
Processing 277/1000
Processing 278/1000
Processing 279/1000
Processing 280/1000
Processing 281/1000
Processing 282/1000
Processing 283/1000
Processing 284/1000
Processing 285/1000
Processing 286/1000
Processing 287/1000
Processing 288/1000
Processing 289/1000
Processing 290/1000
Processing 291/1000
Processing 292/1000
Processing 293/1000
Processing 294/1000
Processing 295/1000
Processing 296/1000
Processing 297/1000
Processing 298/1000
Processing 299/1000
Processing 300/1000
Processing 301/1000
Processing 302/1000
Processing 303/1000
Processing 304/1000
Processing 305/1000
Processing 306/1000
Processing 307/1000
Processing 308/1000
Processing 309/1000
Processing 310/1000
Processing 311/1000
Processing 312/1000
Processing 313/1000
Processing 314/1000
Processing 315/1000
Processing 316/1000
Processing 317/1000
Processing 318/1000
Processing 319/1000
Processing 320/1000
Processing 321/1000
Processing 322/1000
Processing 323/1000
Processing 324/1000
Processing 325/1000
Processing 326/1000
Processing 327/1000
Processing 328/1000
Processing 329/1000
Processing 330/1000
Processing 331/1000
Processing 332/1000
Processing 333/1000
Processing 334/1000
Processing 335/1000
Processing 336/1000
Processing 337/1000
Processing 338/1000
Processing 339/1000
Processing 340/1000
Processing 341/1000
Processing 342/1000
Processing 343/1000
Processing 344/1000
Processing 345/1000
Processing 346/1000
Processing 347/1000
Processing 348/1000
Processing 349/1000
Processing 350/1000
Processing 351/1000
Processing 352/1000
Processing 353/1000
Processing 354/1000
Processing 355/1000
Processing 356/1000
Processing 357/1000
Processing 358/1000
Processing 359/1000
Processing 360/1000
Processing 361/1000
Processing 362/1000
Processing 363/1000
Processing 364/1000
Processing 365/1000
Processing 366/1000
Processing 367/1000
Processing 368/1000
Processing 369/1000
Processing 370/1000
Processing 371/1000
Processing 372/1000
Processing 373/1000
Processing 374/1000
Processing 375/1000
Processing 376/1000
Processing 377/1000
Processing 378/1000
Processing 379/1000
Processing 380/1000
Processing 381/1000
Processing 382/1000
Processing 383/1000
Processing 384/1000
Processing 385/1000
Processing 386/1000
Processing 387/1000
Processing 388/1000
Processing 389/1000
Processing 390/1000
Processing 391/1000
Processing 392/1000
Processing 393/1000
Processing 394/1000
Processing 395/1000
Processing 396/1000
Processing 397/1000
Processing 398/1000
Processing 399/1000
Processing 400/1000
Processing 401/1000
Processing 402/1000
Processing 403/1000
Processing 404/1000
Processing 405/1000
Processing 406/1000
Processing 407/1000
Processing 408/1000
Processing 409/1000
Processing 410/1000
Processing 411/1000
Processing 412/1000
Processing 413/1000
Processing 414/1000
Processing 415/1000
Processing 416/1000
Processing 417/1000
Processing 418/1000
Processing 419/1000
Processing 420/1000
Processing 421/1000
Processing 422/1000
Processing 423/1000
Processing 424/1000
Processing 425/1000
Processing 426/1000
Processing 427/1000
Processing 428/1000
Processing 429/1000
Processing 430/1000
Processing 431/1000
Processing 432/1000
Processing 433/1000
Processing 434/1000
Processing 435/1000
Processing 436/1000
Processing 437/1000
Processing 438/1000
Processing 439/1000
Processing 440/1000
Processing 441/1000
Processing 442/1000
Processing 443/1000
Processing 444/1000
Processing 445/1000
Processing 446/1000
Processing 447/1000
Processing 448/1000
Processing 449/1000
Processing 450/1000
Processing 451/1000
Processing 452/1000
Processing 453/1000
Processing 454/1000
Processing 455/1000
Processing 456/1000
Processing 457/1000
Processing 458/1000
Processing 459/1000
Processing 460/1000
Processing 461/1000
Processing 462/1000
Processing 463/1000
Processing 464/1000
Processing 465/1000
Processing 466/1000
Processing 467/1000
Processing 468/1000
Processing 469/1000
Processing 470/1000
Processing 471/1000
Processing 472/1000
Processing 473/1000
Processing 474/1000
Processing 475/1000
Processing 476/1000
Processing 477/1000
Processing 478/1000
Processing 479/1000
Processing 480/1000
Processing 481/1000
Processing 482/1000
Processing 483/1000
Processing 484/1000
Processing 485/1000
Processing 486/1000
Processing 487/1000
Processing 488/1000
Processing 489/1000
Processing 490/1000
Processing 491/1000
Processing 492/1000
Processing 493/1000
Processing 494/1000
Processing 495/1000
Processing 496/1000
Processing 497/1000
Processing 498/1000
Processing 499/1000
Processing 500/1000
Processing 501/1000
Processing 502/1000
Processing 503/1000
Processing 504/1000
Processing 505/1000
Processing 506/1000
Processing 507/1000
Processing 508/1000
Processing 509/1000
Processing 510/1000
Processing 511/1000
Processing 512/1000
Processing 513/1000
Processing 514/1000
Processing 515/1000
Processing 516/1000
Processing 517/1000
Processing 518/1000
Processing 519/1000
Processing 520/1000
Processing 521/1000
Processing 522/1000
Processing 523/1000
Processing 524/1000
Processing 525/1000
Processing 526/1000
Processing 527/1000
Processing 528/1000
Processing 529/1000
Processing 530/1000
Processing 531/1000
Processing 532/1000
Processing 533/1000
Processing 534/1000
Processing 535/1000
Processing 536/1000
Processing 537/1000
Processing 538/1000
Processing 539/1000
Processing 540/1000
Processing 541/1000
Processing 542/1000
Processing 543/1000
Processing 544/1000
Processing 545/1000
Processing 546/1000
Processing 547/1000
Processing 548/1000
Processing 549/1000
Processing 550/1000
Processing 551/1000
Processing 552/1000
Processing 553/1000
Processing 554/1000
Processing 555/1000
Processing 556/1000
Processing 557/1000
Processing 558/1000
Processing 559/1000
Processing 560/1000
Processing 561/1000
Processing 562/1000
Processing 563/1000
Processing 564/1000
Processing 565/1000
Processing 566/1000
Processing 567/1000
Processing 568/1000
Processing 569/1000
Processing 570/1000
Processing 571/1000
Processing 572/1000
Processing 573/1000
Processing 574/1000
Processing 575/1000
Processing 576/1000
Processing 577/1000
Processing 578/1000
Processing 579/1000
Processing 580/1000
Processing 581/1000
Processing 582/1000
Processing 583/1000
Processing 584/1000
Processing 585/1000
Processing 586/1000
Processing 587/1000
Processing 588/1000
Processing 589/1000
Processing 590/1000
Processing 591/1000
Processing 592/1000
Processing 593/1000
Processing 594/1000
Processing 595/1000
Processing 596/1000
Processing 597/1000
Processing 598/1000
Processing 599/1000
Processing 600/1000
Processing 601/1000
Processing 602/1000
Processing 603/1000
Processing 604/1000
Processing 605/1000
Processing 606/1000
Processing 607/1000
Processing 608/1000
Processing 609/1000
Processing 610/1000
Processing 611/1000
Processing 612/1000
Processing 613/1000
Processing 614/1000
Processing 615/1000
Processing 616/1000
Processing 617/1000
Processing 618/1000
Processing 619/1000
Processing 620/1000
Processing 621/1000
Processing 622/1000
Processing 623/1000
Processing 624/1000
Processing 625/1000
Processing 626/1000
Processing 627/1000
Processing 628/1000
Processing 629/1000
Processing 630/1000
Processing 631/1000
Processing 632/1000
Processing 633/1000
Processing 634/1000
Processing 635/1000
Processing 636/1000
Processing 637/1000
Processing 638/1000
Processing 639/1000
Processing 640/1000
Processing 641/1000
Processing 642/1000
Processing 643/1000
Processing 644/1000
Processing 645/1000
Processing 646/1000
Processing 647/1000
Processing 648/1000
Processing 649/1000
Processing 650/1000
Processing 651/1000
Processing 652/1000
Processing 653/1000
Processing 654/1000
Processing 655/1000
Processing 656/1000
Processing 657/1000
Processing 658/1000
Processing 659/1000
Processing 660/1000
Processing 661/1000
Processing 662/1000
Processing 663/1000
Processing 664/1000
Processing 665/1000
Processing 666/1000
Processing 667/1000
Processing 668/1000
Processing 669/1000
Processing 670/1000
Processing 671/1000
Processing 672/1000
Processing 673/1000
Processing 674/1000
Processing 675/1000
Processing 676/1000
Processing 677/1000
Processing 678/1000
Processing 679/1000
Processing 680/1000
Processing 681/1000
Processing 682/1000
Processing 683/1000
Processing 684/1000
Processing 685/1000
Processing 686/1000
Processing 687/1000
Processing 688/1000
Processing 689/1000
Processing 690/1000
Processing 691/1000
Processing 692/1000
Processing 693/1000
Processing 694/1000
Processing 695/1000
Processing 696/1000
Processing 697/1000
Processing 698/1000
Processing 699/1000
Processing 700/1000
Processing 701/1000
Processing 702/1000
Processing 703/1000
Processing 704/1000
Processing 705/1000
Processing 706/1000
Processing 707/1000
Processing 708/1000
Processing 709/1000
Processing 710/1000
Processing 711/1000
Processing 712/1000
Processing 713/1000
Processing 714/1000
Processing 715/1000
Processing 716/1000
Processing 717/1000
Processing 718/1000
Processing 719/1000
Processing 720/1000
Processing 721/1000
Processing 722/1000
Processing 723/1000
Processing 724/1000
Processing 725/1000
Processing 726/1000
Processing 727/1000
Processing 728/1000
Processing 729/1000
Processing 730/1000
Processing 731/1000
Processing 732/1000
Processing 733/1000
Processing 734/1000
Processing 735/1000
Processing 736/1000
Processing 737/1000
Processing 738/1000
Processing 739/1000
Processing 740/1000
Processing 741/1000
Processing 742/1000
Processing 743/1000
Processing 744/1000
Processing 745/1000
Processing 746/1000
Processing 747/1000
Processing 748/1000
Processing 749/1000
Processing 750/1000
Processing 751/1000
Processing 752/1000
Processing 753/1000
Processing 754/1000
Processing 755/1000
Processing 756/1000
Processing 757/1000
Processing 758/1000
Processing 759/1000
Processing 760/1000
Processing 761/1000
Processing 762/1000
Processing 763/1000
Processing 764/1000
Processing 765/1000
Processing 766/1000
Processing 767/1000
Processing 768/1000
Processing 769/1000
Processing 770/1000
Processing 771/1000
Processing 772/1000
Processing 773/1000
Processing 774/1000
Processing 775/1000
Processing 776/1000
Processing 777/1000
Processing 778/1000
Processing 779/1000
Processing 780/1000
Processing 781/1000
Processing 782/1000
Processing 783/1000
Processing 784/1000
Processing 785/1000
Processing 786/1000
Processing 787/1000
Processing 788/1000
Processing 789/1000
Processing 790/1000
Processing 791/1000
Processing 792/1000
Processing 793/1000
Processing 794/1000
Processing 795/1000
Processing 796/1000
Processing 797/1000
Processing 798/1000
Processing 799/1000
Processing 800/1000
Processing 801/1000
Processing 802/1000
Processing 803/1000
Processing 804/1000
Processing 805/1000
Processing 806/1000
Processing 807/1000
Processing 808/1000
Processing 809/1000
Processing 810/1000
Processing 811/1000
Processing 812/1000
Processing 813/1000
Processing 814/1000
Processing 815/1000
Processing 816/1000
Processing 817/1000
Processing 818/1000
Processing 819/1000
Processing 820/1000
Processing 821/1000
Processing 822/1000
Processing 823/1000
Processing 824/1000
Processing 825/1000
Processing 826/1000
Processing 827/1000
Processing 828/1000
Processing 829/1000
Processing 830/1000
Processing 831/1000
Processing 832/1000
Processing 833/1000
Processing 834/1000
Processing 835/1000
Processing 836/1000
Processing 837/1000
Processing 838/1000
Processing 839/1000
Processing 840/1000
Processing 841/1000
Processing 842/1000
Processing 843/1000
Processing 844/1000
Processing 845/1000
Processing 846/1000
Processing 847/1000
Processing 848/1000
Processing 849/1000
Processing 850/1000
Processing 851/1000
Processing 852/1000
Processing 853/1000
Processing 854/1000
Processing 855/1000
Processing 856/1000
Processing 857/1000
Processing 858/1000
Processing 859/1000
Processing 860/1000
Processing 861/1000
Processing 862/1000
Processing 863/1000
Processing 864/1000
Processing 865/1000
Processing 866/1000
Processing 867/1000
Processing 868/1000
Processing 869/1000
Processing 870/1000
Processing 871/1000
Processing 872/1000
Processing 873/1000
Processing 874/1000
Processing 875/1000
Processing 876/1000
Processing 877/1000
Processing 878/1000
Processing 879/1000
Processing 880/1000
Processing 881/1000
Processing 882/1000
Processing 883/1000
Processing 884/1000
Processing 885/1000
Processing 886/1000
Processing 887/1000
Processing 888/1000
Processing 889/1000
Processing 890/1000
Processing 891/1000
Processing 892/1000
Processing 893/1000
Processing 894/1000
Processing 895/1000
Processing 896/1000
Processing 897/1000
Processing 898/1000
Processing 899/1000
Processing 900/1000
Processing 901/1000
Processing 902/1000
Processing 903/1000
Processing 904/1000
Processing 905/1000
Processing 906/1000
Processing 907/1000
Processing 908/1000
Processing 909/1000
Processing 910/1000
Processing 911/1000
Processing 912/1000
Processing 913/1000
Processing 914/1000
Processing 915/1000
Processing 916/1000
Processing 917/1000
Processing 918/1000
Processing 919/1000
Processing 920/1000
Processing 921/1000
Processing 922/1000
Processing 923/1000
Processing 924/1000
Processing 925/1000
Processing 926/1000
Processing 927/1000
Processing 928/1000
Processing 929/1000
Processing 930/1000
Processing 931/1000
Processing 932/1000
Processing 933/1000
Processing 934/1000
Processing 935/1000
Processing 936/1000
Processing 937/1000
Processing 938/1000
Processing 939/1000
Processing 940/1000
Processing 941/1000
Processing 942/1000
Processing 943/1000
Processing 944/1000
Processing 945/1000
Processing 946/1000
Processing 947/1000
Processing 948/1000
Processing 949/1000
Processing 950/1000
Processing 951/1000
Processing 952/1000
Processing 953/1000
Processing 954/1000
Processing 955/1000
Processing 956/1000
Processing 957/1000
Processing 958/1000
Processing 959/1000
Processing 960/1000
Processing 961/1000
Processing 962/1000
Processing 963/1000
Processing 964/1000
Processing 965/1000
Processing 966/1000
Processing 967/1000
Processing 968/1000
Processing 969/1000
Processing 970/1000
Processing 971/1000
Processing 972/1000
Processing 973/1000
Processing 974/1000
Processing 975/1000
Processing 976/1000
Processing 977/1000
Processing 978/1000
Processing 979/1000
Processing 980/1000
Processing 981/1000
Processing 982/1000
Processing 983/1000
Processing 984/1000
Processing 985/1000
Processing 986/1000
Processing 987/1000
Processing 988/1000
Processing 989/1000
Processing 990/1000
Processing 991/1000
Processing 992/1000
Processing 993/1000
Processing 994/1000
Processing 995/1000
Processing 996/1000
Processing 997/1000
Processing 998/1000
Processing 999/1000
Processing 1000/1000

### Checking Results

In [16]:
df.head()

print(df["Category"].value_counts())

Category
Default               152
Nonfiction            110
Sequential Art         75
Add a comment          67
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Poetry                 19
Classics               19
History                18
Horror                 17
Womens Fiction         17
Science Fiction        16
Science                14
Music                  13
Business               12
Travel                 11
Thriller               11
Philosophy             11
Humor                  10
Autobiography           9
Art                     8
Religion                7
Psychology              7
Spirituality            6
New Adult               6
Christian Fiction       6
Self Help               5
Biography               5
Sports and Games        5
Health                  4
Politics                3
Contemporary            3
Christian               3
Historical              2
Crime                   1
Erotica                 1
Cultural                1
Novels                  1
Short Stories           1
Suspense                1
Academic                1
Adult Fiction           1
Parenting               1
Paranormal              1
Name: count, dtype: int64

### Saving Updated Dataset

In [17]:
df.to_csv("books_with_category.csv", index=False)

print("Category added successfully!")

Category added successfully!

In [19]:
df.head(1000)

,Title,Price,Rating,Availability,Product_URL,Category
0,A Light in the Attic,51.77,3,In stock,http://books.toscrape.com/catalogue/a-light-in...,Poetry
1,Tipping the Velvet,53.74,1,In stock,http://books.toscrape.com/catalogue/tipping-th...,Historical Fiction
2,Soumission,50.10,1,In stock,http://books.toscrape.com/catalogue/soumission...,Fiction
3,Sharp Objects,47.82,4,In stock,http://books.toscrape.com/catalogue/sharp-obje...,Mystery
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,http://books.toscrape.com/catalogue/sapiens-a-...,History
...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,1,In stock,http://books.toscrape.com/catalogue/alice-in-w...,Classics
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,4,In stock,http://books.toscrape.com/catalogue/ajin-demi-...,Sequential Art
997,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,http://books.toscrape.com/catalogue/a-spys-dev...,Historical Fiction
998,1st to Die (Women's Murder Club #1),53.98,1,In stock,http://books.toscrape.com/catalogue/1st-to-die...,Mystery
999,"1,000 Places to See Before You Die",26.08,5,In stock,http://books.toscrape.com/catalogue/1000-place...,Travel